export const erc20Abi = [
  { name: 'approve',   type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }],
    outputs: [{ type: 'bool' }] },
  { name: 'balanceOf', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'allowance', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address' }, { name: 'spender', type: 'address' }],
    outputs: [{ type: 'uint256' }] },
] as const

export const stakeManagerAbi = [
  { name: 'stake',            type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { name: 'requestUnstake',   type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { name: 'withdraw',         type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
  { name: 'stakes',           type: 'function', stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: 'amount', type: 'uint256' }, { name: 'unlocksAt', type: 'uint256' }] },
  { name: 'withdrawCooldown', type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'treasury',         type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'protocolSlashBp',  type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
] as const

export const registryAbi = [
  { name: 'minimumStakeRequired', type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'providerCount',        type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'stakeManager',         type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'providers', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [
      { name: 'owner',           type: 'address' },
      { name: 'metadataURI',     type: 'string'  },
      { name: 'payoutAddress',   type: 'address' },
      { name: 'revenueSplitter', type: 'address' },
      { name: 'active',          type: 'bool'    },
      { name: 'createdAt',       type: 'uint256' },
    ] },
  { name: 'endpoints', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'endpointId', type: 'bytes32' }],
    outputs: [
      { name: 'endpointId',    type: 'bytes32' },
      { name: 'provider',      type: 'address' },
      { name: 'path',          type: 'string'  },
      { name: 'method',        type: 'string'  },
      { name: 'integrityHash', type: 'bytes32' },
      { name: 'version',       type: 'uint256' },
      { name: 'active',        type: 'bool'    },
      { name: 'checkedAt',     type: 'uint256' },
      { name: 'createdAt',     type: 'uint256' },
    ] },
  { name: 'registerEndpoint', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'providerId',    type: 'uint256' },
      { name: 'path',          type: 'string'  },
      { name: 'method',        type: 'string'  },
      { name: 'integrityHash', type: 'bytes32' },
    ], outputs: [] },
  { name: 'updateProvider', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'id',              type: 'uint256' },
      { name: 'metadataURI',     type: 'string'  },
      { name: 'payoutAddress',   type: 'address' },
      { name: 'revenueSplitter', type: 'address' },
    ], outputs: [] },
  { name: 'EndpointRegistered', type: 'event',
    inputs: [
      { name: 'endpointId', type: 'bytes32', indexed: true  },
      { name: 'provider',   type: 'address', indexed: true  },
      { name: 'providerId', type: 'uint256', indexed: true  },
    ] },
  { name: 'ProviderRegistered', type: 'event',
    inputs: [
      { name: 'id',    type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
    ] },
] as const

export const factoryAbi = [
  { name: 'USDC',               type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'registry',           type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'protocolTreasuryBp', type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'providerCount',      type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'deployProvider', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'name',             type: 'string'  },
      { name: 'symbol',           type: 'string'  },
      { name: 'vaultBp',          type: 'uint256' },
      { name: 'genesisShares',    type: 'uint256' },
      { name: 'genesisRecipient', type: 'address' },
      { name: 'genesisDeposit',   type: 'uint256' },
      { name: 'providerTreasury', type: 'address' },
      { name: 'revenueShareBp',   type: 'uint256' },
      { name: 'rsShares',         type: 'uint256' },
      { name: 'rsRecipient',      type: 'address' },
      { name: 'metadataURI',      type: 'string'  },
    ], outputs: [] },
  { name: 'ProviderDeployed', type: 'event',
    inputs: [
      { name: 'providerId',   type: 'uint256', indexed: true  },
      { name: 'owner',        type: 'address', indexed: true  },
      { name: 'vault',        type: 'address', indexed: false },
      { name: 'splitter',     type: 'address', indexed: false },
      { name: 'revenueShare', type: 'address', indexed: false },
    ] },
] as const

export const challengeManagerAbi = [
  { name: 'challengeFee',   type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'slashBp',        type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'challengeCount', type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'forwarder',      type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'challenges', type: 'function', stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [
      { name: 'challenger',  type: 'address' },
      { name: 'endpointId',  type: 'bytes32' },
      { name: 'status',      type: 'uint8'   },
    ] },
  { name: 'openChallenge', type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'endpointId', type: 'bytes32' }], outputs: [] },
  { name: 'ChallengeOpened', type: 'event',
    inputs: [
      { name: 'id',             type: 'uint256', indexed: true  },
      { name: 'endpointId',     type: 'bytes32', indexed: true  },
      { name: 'path',           type: 'string',  indexed: false },
      { name: 'method',         type: 'string',  indexed: false },
      { name: 'integrityHash',  type: 'bytes32', indexed: false },
    ] },
  { name: 'ChallengeResolved', type: 'event',
    inputs: [
      { name: 'id',     type: 'uint256', indexed: true },
      { name: 'status', type: 'uint8',   indexed: false },
    ] },
] as const

export const vaultAbi = [
  { name: 'totalSupply',      type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'totalAssets',      type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'depositsEnabled',  type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'bool' }] },
  { name: 'genesisComplete',  type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'bool' }] },
  { name: 'balanceOf',        type: 'function', stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'convertToAssets',  type: 'function', stateMutability: 'view',
    inputs: [{ name: 'shares', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
  { name: 'openDeposits', type: 'function', stateMutability: 'nonpayable',
    inputs: [], outputs: [] },
  { name: 'deposit', type: 'function', stateMutability: 'nonpayable',
    inputs: [{ name: 'assets', type: 'uint256' }, { name: 'receiver', type: 'address' }],
    outputs: [{ type: 'uint256' }] },
  { name: 'redeem', type: 'function', stateMutability: 'nonpayable',
    inputs: [
      { name: 'shares',   type: 'uint256' },
      { name: 'receiver', type: 'address' },
      { name: 'owner',    type: 'address' },
    ], outputs: [{ type: 'uint256' }] },
] as const

export const splitterAbi = [
  { name: 'pendingDistribution', type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'protocolTreasuryBp',  type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'providerTreasuryBp',  type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'revenueShareBp',      type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'vaultBp',             type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'vault',               type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'protocolTreasury',    type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'providerTreasury',    type: 'function', stateMutability: 'view',
    inputs: [], outputs: [{ type: 'address' }] },
  { name: 'distribute', type: 'function', stateMutability: 'nonpayable',
    inputs: [], outputs: [] },
] as const
